name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Find and Upload APK
      run: |
        APK_PATH=$(find . -name "*.apk" | head -n 1)
        echo "APK_PATH=${APK_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Android-APK
        path: ${{ env.APK_PATH }}
